### ISSUE TITLE
Non-Ukraine questions?

### ISSUE THREAD

**Issue by adam-binks** [nikosbosse/Metaculus-Twitter-bot#18]
What do you think about either:

A) Opening the bot up to all Metaculus questions

B) Making a second bot which is all Metaculus questions (or all non-Ukraine questions)

For me personally, I'm most interested in updates in longtermist/x-risk questions, even though I imagine they're rarer. So it'd be great to see these on Twitter as they happen.

(E.g. motivating hypothetical example: everyone is talking about a new Deepmind paper, and then you see a tweet saying that Metaculus's AGI by 2050 question has just had +10%!)

**Comment by edomt** [comment]
I'd be very much in favor of it, and I _think_ it's more or less what @nikosbosse has in mind as well :) 

The only question is whether it's worth doing it in steps, like maybe adding 1 new project (e.g. 1313 on AI?), rather than adding all Metaculus questions right away (which could result in too many alerts).

**Comment by nikosbosse** [comment]
I'm all in favour :) 
There are two constraints: 
- the number of alerts we send
- the function currently runs on google cloud and there is a time limit. I thought it was 5 min, but apparently it's 9min. We could of course also just run it on Metaculus servers at some point.. 

Some strategic questions: 
- do we want to have one bot for all, or several bots with several topics people can choose to follow?
- do we want to get rid of the 5h/5% alert to reduce the number of alerts?

**Comment by edomt** [comment]
> do we want to have one bot for all, or several bots with several topics people can choose to follow?

I'd say the same one? Seems like it would break the "momentum" of the existing bot (which already has 2.5K followers!) if a bunch of other ones are created.

> do we want to get rid of the 5h/5% alert to reduce the number of alerts?

Possibly, yes - whenever I see 5h/5% alerts on Twitter I always find them less insightful than the 24h/10% ones.

**Comment by nikosbosse** [comment]
Agree on both questions in principle. 
I would kind of like to have even longer horizons than 24h

**Comment by adam-binks** [comment]
If we're extending the existing bot, we could include a keyword for non-Ukraine questions so that people can [mute it](https://help.twitter.com/en/using-twitter/advanced-twitter-mute-options#:~:text=Click%20the%20Privacy%20and%20safety%20tab%2C%20then%20click%20Mute%20and%20block.,-Step%203&text=Click%20Muted%20words.,-Step%204&text=Click%20the%20word%20or%20hashtag,like%20to%20edit%20or%20unmute.&text=Step%205-,Change%20the%20Mute%20from%20or,time%20selections%2C%20and%20click%20Save) if they want to only see Ukraine stuff. But I think this might be cluttered/unnecessary (and maybe good to bring more attention to other areas!)

> whenever I see 5h/5% alerts on Twitter I always find them less insightful than the 24h/10% ones

I agree! More likely to be signal than noise with 10% :)

**Comment by nikosbosse** [comment]
![image](https://user-images.githubusercontent.com/37978797/161811010-20e27a78-c179-43b1-bea6-1dd3ee0fb7ff.png)

I guess the people have spoken :) 
Now we have to think a bit about how we open up to new questions. Some thoughts: 
- For the start we could manually add new relevant projects / tournaments? 
- We should get rid of the 5% threshold
- We need to think about the 'new questions' thing. If we tweet about *every* new question than things will become messy at some point. One suggestion that Sylvain made was the following: Instead of filtering for a period, we could filter for e.g. a certain number of forecasts or a certain number of votes on the question. So we would only include questions which pass that threshold and tweet about a 'new' question once the moment it passes that threshold.
